# -*- coding: utf-8 -*-
"""K2T.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JCmlFqWFv9oBFxcveXEa1i86lxCS16lT

# Keytotext Demo
"""

!pip install keytotext --upgrade

import os

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.

# %cd /content/drive/MyDrive/adlfinal
!ls

from keytotext import pipeline

nlp = pipeline("mrm8488/t5-base-finetuned-common_gen")

import json
f=open('keywords.json')
j=json.load(f)
texts={}

c=0
for k in j:
    texts[k]={}
    for w in j[k]:
      c+=1
      print(c)
      texts[k][w]=(nlp([w]))

with open('./keytexts.json', 'w') as fp:
    json.dump(texts, fp)

f=open('./keytexts.json')
j=json.load(f)
for k in j:
  for w in j[k]:
    print(j[k][w])